apiVersion: v1
data:
  default.conf: |
    server {
        listen 80 default_server;
        server_name _;

        location / {
            return 200 '$hostname\n Hello World! from EPAM K8s-network hw\n nginx $NGINX_VERSION\n';
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm
